version: '3.9'
services:
  web:
    env_file: .env
    build: .
    ports:
        - "5000:5000"
    volumes:
        - .:/code
    depends_on:
        - db
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
